services:
  - type: web
    name: vendor-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: vendor-mongodb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
        length: 32
      - key: JWT_REFRESH_SECRET
        generateValue: true
        length: 32
      - key: JWT_EXPIRES_IN
        value: "24h"
      - key: JWT_REFRESH_EXPIRES_IN
        value: "30d"
      - key: CORS_ORIGIN
        value: "https://vendor-frontend.onrender.com"
      - key: RATE_LIMIT_WINDOW_MS
        value: "900000"
      - key: RATE_LIMIT_MAX_REQUESTS
        value: "100"

databases:
  - name: vendor-mongodb
    databaseName: vendor_database
    user: vendor_user
    plan: free