# Generated by Django 5.1.6 on 2025-07-06 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_company_description_company_is_public_and_more'),
    ]

    operations = [
    ]
