# Generated by Django 5.1.6 on 2025-06-22 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_employee_retailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='app.employee'),
        ),
    ]
