# Generated by Django 5.1.6 on 2025-07-06 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20250706_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='Retailer',
        ),
        migrations.AlterField(
            model_name='order',
            name='retailer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app.retailerprofile'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='retailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='app.retailerprofile'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='company',
        ),
        migrations.AddField(
            model_name='retailerprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='retailerprofile',
            name='state',
            field=models.CharField(default='Tamil Nadu', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='retailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='app.retailerprofile'),
        ),
        migrations.DeleteModel(
            name='Retailer',
        ),
    ]
